# Generated by Django 2.0.2 on 2018-03-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_user_img_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.CharField(max_length=100, verbose_name='받는사람')),
                ('title_email', models.CharField(max_length=100, verbose_name='제목')),
                ('message_email', models.TextField(verbose_name='내용')),
            ],
        ),
    ]
